### ISSUE TITLE
TPB05: [Sugestão] Utilizar Sass ou Styled Component para facilitar o desenvolvimento de estilos

### ISSUE THREAD

**Issue by priscilaandreani** [leandrosax10/saudeDaRua#1]
Através de um pré processador de CSS conseguimos:
- Melhorar nossa experiência de desenvolvimento
- Facilidade pra codar (sem a necessidade de digital o hexadecimal todas as vezes).
- Garantimos a utilização das cores corretas nos layouts (uma vez que são pré determinadas)
- Utilizar variáveis

_Sass ou StyledComponent são apenas sugestões do que eu gosto de usar, mas escolham a que tiverem mais afinidade._

**Comment by priscilaandreani** [comment]
Aqui também devemos prever a criação de um "estilo global" para a aplicação.

**Comment by priscilaandreani** [comment]
@leandrosax10 pode fechar essa issue quando mergear a TPB05 ;)

**Comment by leandrosax10** [comment]
Completo
