### ISSUE TITLE
TPB02: [Sugestão]  ESLint, Prettier e EditorConfig

### ISSUE THREAD

**Issue by priscilaandreani** [leandrosax10/saudeDaRua#4]
Como estamos trabalhando num projeto compartilhado, é uma boa prática adotarmos um padrão ao nosso código.

[Aqui tem um tutorial da Rocketseat de como podemos fazer isso.](https://www.notion.so/ESLint-Prettier-e-EditorConfig-7da7de5f981742aebbba2c1ae7d44474)

**Comment by Maridh** [comment]
Feito

**Comment by Maridh** [comment]
https://www.youtube.com/watch?v=TI4v4Y8yRjw
